Interactions tab
privadonetwork/privado-wallet pull request #61
Opened 2021-11-09 17:24 UTC by gustavoeffting

2021-11-09 17:25 UTC, gustavoeffting commented
_note: some endpoints improvements need to be done_

2021-11-10 12:08 UTC, AlbertoElias commented on src/components/activities/MyActivity.tsx
> +                {/* ProofStatus.Success is sent here because whether the user has an interaction it means that he is already verified */}
ProofStatus.Success signals if a user already has an interaction, which means they are already verified

2021-11-10 12:09 UTC, AlbertoElias requested changes
Couple small comments

2021-11-10 12:09 UTC, AlbertoElias commented on src/components/activities/MyActivity.tsx
> +          allInteractions.interactions &&
maybe with allInteractions?.interactions is enough and you can avoid double check

2021-11-11 10:00 UTC, cneuro commented on src/context/actions.ts
> +export function userCleanAllInteractions(dispatch: React.Dispatch<ContextAppAction>): void {
When do you ever call this action? What are the use cases here?

2021-11-11 16:30 UTC, gustavoeffting commented on src/context/actions.ts
> +export function userCleanAllInteractions(dispatch: React.Dispatch<ContextAppAction>): void {
@cneuro I forgot to add this function in the useEffect return. It's used to clean up the state variable and guarantee that it will be up to date when the user get back to the page

2021-11-11 17:14 UTC, cneuro commented on src/context/actions.ts
> +export function userCleanAllInteractions(dispatch: React.Dispatch<ContextAppAction>): void {
Without analyzing this in detail myself, needing to do this kind of thing isn't normal. The state should always be updated to what it needs to be when it is requested (and displayed or used) - if it's out of date while it is not needed then it doesn't matter. The logic being that if you're doing this here, then you would need this arbitrary "cleaning up" process for the state every single time for every single piece of state that might be outdated.

It seems like you need to look at your actions and state lifecycle to make sure why you are having issues with out of date state in the first place. My recommendation is to look for when you are requesting it and displaying it and really analyzing why you would need this.

2021-11-11 17:36 UTC, AlbertoElias commented on src/context/actions.ts
> +export function userCleanAllInteractions(dispatch: React.Dispatch<ContextAppAction>): void {
I think this is used in many places. I agree with the suggestion to reconsider the lifecycle, but as it's a deeper issue with the application, probably worth leaving to a separate PR.

2021-11-11 18:20 UTC, gustavoeffting commented on src/context/actions.ts
> +export function userCleanAllInteractions(dispatch: React.Dispatch<ContextAppAction>): void {
Yep, I've saw some places following this pattern I thought was some pattern to avoid old data. But I agree with Chris too. I'll check if it will demand much time to fix here, otherwise I'll do this in another PR.

2021-11-12 10:37 UTC, AlbertoElias approved these changes

2021-11-16 14:20 UTC, merged