All my data
privadonetwork/privado-wallet pull request #62
Opened 2021-11-11 11:30 UTC by gustavoeffting

2021-11-11 17:08 UTC, cneuro requested changes

2021-11-11 17:35 UTC, AlbertoElias commented on src/components/myData/Documents.tsx
> +  const [document] = useState({
Things are hardcoded because the API isn't ready. We wanted to make as much progress regardless

2021-11-11 17:35 UTC, AlbertoElias commented on src/components/myData/Documents.tsx
> +  const [document] = useState({
It's good to mention these details in the PR description @gustavoeffting

2021-11-11 18:19 UTC, AlbertoElias reviewed
Couple comments

2021-11-11 18:19 UTC, AlbertoElias commented on src/components/myData/DetailsTemplate.tsx
> +const DetailsTemplate: FC<detailsProp> = ({ details }) => {
I don't think we need the suffix Template. In the end they are all components and it's implicit. It could be called DataDetails for example

2021-11-11 20:20 UTC, gustavoeffting commented on src/components/myData/Documents.tsx
> +  const [document] = useState({
Yep sorry, forgot to mention

2021-11-12 10:36 UTC, AlbertoElias approved these changes

2021-11-15 13:27 UTC, cneuro commented on src/components/myData/DetailsTemplate.tsx
> +type detailsProp = {
Small thing: all types should be capitalized.

2021-11-15 13:28 UTC, cneuro commented on src/components/my-data/ClaimDetails.tsx
> +type detailsProp = {
Small thing: all types should be capitalized.

2021-11-16 11:28 UTC, AlbertoElias submitted a review, later dismissed

2021-11-16 13:04 UTC, cneuro approved these changes

2021-11-16 16:50 UTC, AlbertoElias approved these changes

2021-11-16 18:29 UTC, cneuro approved these changes

2021-11-18 23:48 UTC, merged